# Generated by Django 5.1.6 on 2025-02-28 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusMessage",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "Id_message",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email_agt", models.EmailField(max_length=254)),
                ("Subject", models.CharField(max_length=255)),
                ("body_message", models.TextField()),
                ("date_recp_message", models.DateTimeField(auto_now_add=True)),
                ("Requete_msg", models.TextField(blank=True, null=True)),
                (
                    "Message_env",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("Date_env_message", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="EmailReporting.statusmessage",
                    ),
                ),
            ],
        ),
    ]
